// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssypqkkhczpaydrtgwcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzeXBxa2toY3pwYXlkcnRnd2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDEwMjAsImV4cCI6MjA2NzU3NzAyMH0.o1xzIuTHoF8HqXwgGYKfvExvtpYlycA9AalfGqYGUgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});